version: '3.7'

services: 
    database:
        image: mongo
        container_name: 'database-server'
        env_file: './docker/mongo/.env'
        expose: 
            - '27017'
        volumes: 
            -   type: volume
                source: database-data
                target: /data/db
            -   type: bind
                source: ./docker/mongo/scripts/script.js
                target: /docker-entrypoint-initdb.d/script.js
            -   type: bind
                source: ./docker/mongo/mongod.conf
                target: /etc/mongo/mongod.conf
        command: 
            - '--config'
            - '/etc/mongo/mongod.conf'
        restart: 'unless-stopped'
    node-web:
        build:
            context: ./docker/node
            dockerfile: Dockerfile
            args:
                PORT: 3000
        image: node-console:v10.0
        container_name: 'node-server'
        volumes:
            -   type: bind
                source: ./package.json
                target: /app/package.json
            -   type: bind
                source: ./server
                target: /app/server
        ports:
            # - '3000:3000'
            -   target: 3000
                published: 8080
                protocol: tcp
                mode: host
        

volumes:
    database-data: